language: elixir
elixir:
  - 1.3.2
  - 1.4.0
otp_release:
  - 18.2
  - 19.1
matrix:
  # We are only interested on the newest/oldest pair
  exclude:
    - elixir: 1.4.0
      otp_release: 18.2
    - elixir: 1.3.2
      otp_release: 19.1
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
before_install:
  - sudo service postgresql stop
  - sudo apt-get -y -qq --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main $PGVERSION >> /etc/apt/sources.list.d/pgdg.list"
  - wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-contrib-$PGVERSION
  - wget https://github.com/fire/snappyex/releases/download/v0.0.1/snappydata-0.7-bin.tar.gz
  - tar xvf snappydata-0.7-bin.tar.gz
  - echo "localhost -client-bind-address=localhost -J-Duser.timezone=UTC -J-Djava.net.preferIPv4Stack=true -heap-size=4096m -thrift-framed-transport=true -thrift-server-port=1531 -thrift-binary-protocol=true" | tee -a ./snappydata-0.7-bin/conf/servers
  - echo "localhost -J-Duser.timezone=UTC -J-Djava.net.preferIPv4Stack=true -heap-size=1024m -thrift-framed-transport=true -thrift-server-port=1530 -thrift-binary-protocol=true" | tee -a ./snappydata-0.7-bin/conf/locators
  - echo "localhost -J-Duser.timezone=UTC -J-Djava.net.preferIPv4Stack=true -spray.can.server.parsing.max-content-length=400m -heap-size=4096m" | tee -a ./snappydata-0.7-bin/conf/leads
  - ./snappydata-0.7-bin/sbin/snappy-start-all.sh 
sudo: required
dist: trusty
cache: apt
env:
  global:
    - PGVERSION=9.6
  matrix:
    - MIX_ENV=test
    - MIX_ENV=pg PGVERSION=9.2
    - MIX_ENV=pg
    - MIX_ENV=mysql
    - MIX_ENV=snappydata
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
before_script:
  - echo "local all postgres trust" | sudo tee /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "host all postgres 127.0.0.1/32 trust" | sudo tee -a /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "host all postgrex_md5_pw 127.0.0.1/32 md5" | sudo tee -a /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "host all postgrex_cleartext_pw 127.0.0.1/32 password" | sudo tee -a /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo service postgresql restart
script:
  - ECTO_POOL=poolboy mix test || true
  - ECTO_POOL=poolboy mix test
  - ECTO_POOL=sbroker mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - eric.meadows.jonsson@gmail.com
